name: workflowOne
on: [push, workflow_dispatch]
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: install dependencies
        run: npm install
      - name: run lint
        run: npm run lint
      - name: run test
        run: npm test
      - name: run build
        run: npm build
      - name: deploy
        run: echo "deployed ${{github.api_url}}" 
        
        
